name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"          
      - name: Clone Repo
        run: |
          export
          mkdir -p $GITHUB_JOB
          cd $GITHUB_JOB
          git clone https://token:${{ secrets.TOKEN_ELOFUN }}@github.com/elofun/greatBunny.git
          pwd
      - name: build docker
        run: |
          cd $GITHUB_JOB
          pwd
          docker build -t nodejs/v1 .
      - name: push dockerhub
        run: |
          docker tag nodejs/v1:latest kukhanh0812/nginx-proxy:game-0.0.2
          docker push kukhanh0812/nginx-proxy:game-0.0.2
